name: RandomizedProcessMiner-CI/CD-Pipeline

on: [ push ]

jobs:
  build-test-and-deploy-if-master:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Git-Repo
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        cache: 'npm'

    - name: Setup Chrome
      uses: browser-actions/setup-chrome@latest

    - name: Install NPM-Dependencies
      run: npm ci

    - name: Run ESLint
      uses: wearerequired/lint-action@v2.1.0
      with:
        eslint: true
        eslint_args: "--config ./.eslintrc.json './**/*.{ts,html}'"
        neutral_check_on_warning: true

    - name: Run Karma tests headless
      run: npm run github-actions-test

    - name: Build Angular project
      run: npm run github-actions-build

    - name: Deploy to Github Pages if branch is main
      if: ${{ github.ref == 'refs/heads/main' }}
      uses: peaceiris/actions-gh-pages@v3
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          enable_jekyll: true
